# roles/consul/tasks/main.yml

- file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /data/consul/logs
    - /data/consul/data
    - /data/consul/config

- copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "consul", dest: "/usr/local/bin/consul", mode: "0755" }
    - { src: "ui", dest: "/data/consul", mode: "0644" }

- shell: nohup consul agent {{ consul_extra }} \
      -ui-dir /data/consul/ui \
      -data-dir /data/consul/data \
      -config-dir /data/consul/config \
      -node={{ ansible_hostname }} \
      -bind={{ facter_ipaddress_eth1 }} \
      -client=0.0.0.0 \
      >/data/consul/logs/consul.log 2>&1 &

- shell: consul join {{ main_server_ip }}
  when: main_server_ip is defined